#!/bin/bash
#Author:elioudakis, A.M.
#email: elioudakis@isc.tuc.gr

arguments=("$@")
#Iterate the whole program, so many times, as the number of the arguments given
for j in "${arguments[@]}";
do

#Check if the file exists and if it is a regular file
if [ ! -f "$j" ] ;then
	echo "FILE: ${j} ---File does not exist"
    	continue #check the next file
fi

#Create two temporary files, or in case they exist, ensure that they are empty
touch tempX
rm tempX
touch tempX

touch tempY
rm tempY
touch tempY

#Send each column of the file to a temporary file
cut -d':' -f1 ${j}  >tempX
cut -d':' -f2 ${j}  >tempY

#Send each temporary file to a vector
declare -a vectorX
declare -a vectorY

while read line
do
    vectorX+=("$line")
done <./tempX

while read line
do
    vectorY+=("$line")
done <./tempY 

##Check that we have 3 and more values for X and Y
if [ ${#vectorX[@]} -lt 3 ]||[ ${#vectorY[@]} -lt 3 ]; then
	echo "FILE: ${j} --- We need 3 or more values for x and y, in order to calculate the linear regression!"
	unset vectorX
	unset vectorY
	continue #go to the next file
fi

##Starting calculations
length=${#vectorX[@]}               

# sum_x
sum_x=0
for i in "${vectorX[@]}";
do
	sum_x=$(echo "${sum_x}+${i}" |bc)

done

##For a constant X vector
tmp=$(echo "${vectorX[0]}*${length}" |bc)
if (( $(echo "${sum_x} == ${tmp}" | bc) )) ; then
	a=1
	b=$(echo "(-1)*${vectorX[0]}"|bc)
	c=0
	err=0
	echo "FILE: ${j}, a=${a} b=${b} c=${c} err=${err}"	
	unset vectorX
	unset vectorY
	continue
fi

#sum_x2
sum_x2=0
for i in "${vectorX[@]}";
do
	sum_x2=$(echo "${sum_x2}+(${i}*${i})" |bc)
done

# sum_y
sum_y=0
for i in "${vectorY[@]}";
do
	sum_y=$(echo "${sum_y}+${i}" |bc)
done

# sum_xy
sum_xy=0
for  ((i=0; i<length; i++))
do
	sum_xy=$(echo "${sum_xy}+(${vectorX[$i]}*${vectorY[$i]})" |bc)
done



# a,b,c
a=0
a=$(echo "scale=2;(${length}*${sum_xy}-${sum_x}*${sum_y})/(${length}*${sum_x2}-${sum_x}*${sum_x})" |bc)  
b=0
b=$(echo "scale=2;(${sum_y}-(${a}*${sum_x}))/(${length})" |bc)

c=1

#err
err=0
for ((i=0; i<length; i++))
do
   err=$(echo "scale=2;${err}+((${vectorY[$i]}-((${a}*${vectorX[$i]})+${b})))^2" |bc)
	
done

echo "FILE: ${j}, a=${a} b=${b} c=${c} err=${err}"

#Unsetting the vectors
unset vectorX
unset vectorY

done

#End of program
rm tempX
rm tempY
exit 0
